name    'treydock-acpid'
version '0.0.1'
source 'git://github.com/treydock/puppet-acpid.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'acpid module'
description 'acpid module'
project_page 'http://github.com/treydock/puppet-acpid'
dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'